--[[
	  ____         _____ _                   _     
	 |  _ \       / ____| |                 (_)    
	 | |_) |_____| |    | |__   __ _ ___ ___ _ ___ 
	 |  _ <______| |    | '_ \ / _` / __/ __| / __|
	 | |_) |     | |____| | | | (_| \__ \__ \ \__ \
	 |____/       \_____|_| |_|\__,_|___/___/_|___/
	 
	Version 1
--]]

--[[
	
	B-Chassis is a fork of A-Chassis 1.7.2, focusing on stripping down bloat while maintaining compatiability with most existing plugins
	If A-Chassis plugin support does not matter to you, consider using this instead: https://github.com/VanillaEdge/Server-Authoritive-Vehicle
	
	Official B-Chassis GitHub: https://github.com/VanillaEdge/B-Chassis
	Official A-Chassis Github: https://github.com/lisphm/A-Chassis
	
	Please check the releases page for new versions.
	
--]]
